### ISSUE TITLE
Yêu cầu - Thêm nhật ký xoá phiếu nghỉ ốm trên Register và Prescription 

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalregister#10]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **CTY TNHH BỆNH VIỆN MEDIC MIỀN ĐÔNG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_medicmd_xoanghiom`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- Ghi nhận nhật ký xoá Phiếu nghỉ ốm như: tài khoản xoá, phần mềm xoá, máy xoá phiếu, thời gian xoá phiếu,.. để xác định nhân viên xoá phiếu nghỉ ốm

**Comment by nghivanbi** [comment]
Hoàn thành: 26/09/2022

**Comment by nghivanbi** [comment]
![image](https://user-images.githubusercontent.com/91751241/191927979-c51b5027-352b-4789-b70e-43d45a0318cb.png)

**Comment by chauthanhtra** [comment]
anh thêm trên Prescription khám bệnh và trong BANT luôn nha anh

**Comment by nghivanbi** [comment]
OK

**Comment by chauthanhtra** [comment]
Prescription mới đã có ghi nhật ký
