### ISSUE TITLE
Lỗi - Test nhận bệnh khám Lao

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalregister#11]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **ngay_tiep_nhan**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_thotnot_bant_pri`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Test chức năng nhận bệnh bệnh nhân khám Lao
- Khi chọn xem lại thông tin bệnh nhân khám Lao từ danh đã đăng ký thì phần mềm không hiển thị thông tin đăng ký khám lao đã đăng ký
![ảnh](https://user-images.githubusercontent.com/97272332/191643782-b0e1c68b-7b6f-4133-a1b4-fd1faf9ca38b.png)

![ảnh](https://user-images.githubusercontent.com/97272332/191642850-0975c6ae-e5ab-4ef5-af05-e9c7a4a1bbf9.png)

- Khi click chuột vào ô BV điều trị thì không thoát được mà bắt buộc phải chọn 1 mã khó bỏ qua khi làm sai
![ảnh](https://user-images.githubusercontent.com/97272332/191643832-dee76727-f9df-4607-b114-5e3702a064a5.png)

- Khi check bệnh nhân khám lao mà không chọn BV điều trị và ngày chứng nhận vẫn lưu được thông tin (nên thêm ràng buộc)
![ảnh](https://user-images.githubusercontent.com/97272332/191644372-e7c171dd-3787-4133-9f72-2e8559fa05ab.png)

- Khi không check bệnh nhân khám lao vẫn lưu được BV điều trị và ngày chứng nhận (nên thêm ràng buộc)
![ảnh](https://user-images.githubusercontent.com/97272332/191644760-9728304c-74c6-4841-8f61-e49a30b8cf89.png)

* Để giảm lỗi người dùng nhập thiếu thông tin nên có thêm ràng buộc 
![ảnh](https://user-images.githubusercontent.com/97272332/191645044-94440513-959b-4bec-b24b-1acf90ea84bc.png)
* Thêm chức năng chỉnh thông tin bệnh nhân khám Lao trong Hiệu chỉnh thông tin để bệnh nhân đã khám có thể bổ sung thông tin nếu nhận bệnh bị thiếu

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.0923.1](http://www.fsend.vn/download/1puizU1E0qA17c7xbPaTWUkpYxRYeEQI)

**Comment by chauthanhtra** [comment]
thứ 2 em test lại nha. đang có việc khác

**Comment by chauthanhtra** [comment]
Mình có thêm chức năng chỉnh thông tin bệnh nhân khám Lao trong Hiệu chỉnh thông tin để bệnh nhân đã khám (quên nhập thông tin khám Lao) có thể bổ sung thông tin nếu nhận bệnh bị thiếu không anh

**Comment by nghivanbi** [comment]
Cập nhật:
Register: v3.22.0928.2

**Comment by chauthanhtra** [comment]
Hiệu chỉnh thông tin không bỏ chek khám Lao được, bỏ check xoá mã bệnh viện là nó bắt chọn bệnh viện
![ảnh](https://user-images.githubusercontent.com/97272332/192704991-37ac6433-ea50-44e7-a22c-0f31368d6e95.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.0928.3](http://www.fsend.vn/download/w8VD5b-T4sKWW0O7UnA0bHsjS056l1aj)
