### ISSUE TITLE
Yêu cầu - Hỗ trợ Thông tư 36/2021/TT-BYT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalregister#12]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_kqcls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Đề xuất thêm chức năng cho hiệu chỉnh từ bệnh bình thường sang bệnh Lao và ngược lại.

```

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.0928.1](http://www.fsend.vn/download/OUj_BEiYCxXnWD8wmUZatyL4-JGiJPuy)

**Comment by le-an-87** [comment]
Register có cập nhật cho hiệu chỉnh không vậy anh!
chỉnh ở chức năng nào vậy
trong hiệu chỉnh thì em không thấy cho check bệnh Lao
![image](https://user-images.githubusercontent.com/96155021/192682965-389ee370-c80b-482b-8e15-b69141fc78e3.png)

**Comment by nghivanbi** [comment]
![image](https://user-images.githubusercontent.com/91751241/192685598-7922b687-1723-4d83-adf0-3bbaa6548dcf.png)

**Comment by le-an-87** [comment]
đã hỗ trợ chức năng hiệu chỉnh!
