### ISSUE TITLE
Yêu cầu - Xử lý địa chỉ BN lúc nhận bệnh

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalregister#13]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quố c Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92120`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Minh Đức CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_tamminhduc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu lúc nhận bệnh, địa chỉ của BN có chứa ký tự xuống dòng, yêu cầu replace ký tự xuống dòng thành ký tự khoảng cách.
Như hình là bị xuống dòng.
![image](https://user-images.githubusercontent.com/99630883/192728769-8ecd53fe-8e1d-4b94-9fe5-c1812ca99f27.png)

**Comment by nghivanbi** [comment]
Cập nhật: 
Register: [v3.22.0930.1](http://www.fsend.vn/download/Q4cuggmDJMiIKmFSPGJuwq9OK9bLP1rd)
