### ISSUE TITLE
Lỗi - Bảng Thông tin khám của bệnh nhân không Load dữ liệu

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalregister#15]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_dongtay_printer`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Trường hợp: Bệnh nhân khám cho chẩn đoán phòng 1 >>> HỦY KHÁM >>> chuyển phòng 2 khám cấp toa
Register: Báo cáo Lượt đăng ký ban đầu >>> cột Mã BN bấm vào link Bảng thông tin khám của bệnh không load thông tin

```
![image](https://user-images.githubusercontent.com/98437757/194003315-b97a6a7e-9230-4fe9-b10e-7cb799f23991.png)

**Comment by nghivanbi** [comment]
Bệnh nhân này khám 02 phòng:
- Danh lấy chỉ lấy chẩn đoán theo phòng đăng ký ban đầu, chứ không lấy hết các phòng khám.
- Cụ thể trường hợp này đúng vì phòng đầu không có khám.
![image](https://user-images.githubusercontent.com/91751241/195230167-40c55d5b-d63d-4f4d-8785-12a973c4fb40.png)

![image](https://user-images.githubusercontent.com/91751241/195230120-20b3132c-5d90-4917-a10e-b8e9d618b82b.png)

**Comment by minhduc2it** [comment]
Nếu phòng đầu HỦY khám thì load thông tin khám phòng kế tiếp được không anh
