### ISSUE TITLE
Lỗi - Chỉnh đối tượng từ BHYT sang thu phí báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalregister#19]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhbinh_chinhdoituong`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022018364` - _**MaKB**_: `2210006323` - _**NgayKCB**_: `17/10/2022` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng hiệu chỉnh thông tin bệnh ngoại trú khi chỉnh từ đối tượng BHYT sang đối tượng thu phí báo lỗi

```
chỉnh ở Register
![image](https://user-images.githubusercontent.com/96155021/198191583-83b3ea9e-abf8-4bb6-a61b-6b4437e73224.png)
Admin
![image](https://user-images.githubusercontent.com/96155021/198191677-2a779809-d0af-4519-8c99-bb22b1442054.png)

**Comment by nghivanbi** [comment]
thongtu37 = 2 chườn trình lấy giabh07, giadan07, giadv07 nhưng không có áp giá:
![image](https://user-images.githubusercontent.com/91751241/198210684-87f5fde1-4d0f-4984-95f9-5a5e78ed7f27.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.10271](http://www.fsend.vn/download/7j-l6PvPYnuk-b5kGXaW15vkZdzUFnix)

**Comment by le-an-87** [comment]
đã fix!
