### ISSUE TITLE
Yêu cầu - Đăng ký tái khám BANT của BN Khám Lao

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalregister#27]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92137`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Quận Ninh Kiều**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_ttytnk`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu khi lập BANT theo ngày thì ghi nhận thông tin Khám lao vào dữ liệu, để lần sau khi BN đăng ký tái khám, tại form tái khám BANT hiển thị thêm thông tin khám lao để người dùng cập nhật là lưu lại.

**Comment by lqbinh1987** [comment]
Nhờ a @nghivanbi xem lỗi này dùm.

**Comment by nghivanbi** [comment]
Này bệnh án thanh toán theo lần tái khám hả?

**Comment by lqbinh1987** [comment]
Đúng rồi anh, thanh toán theo lần tái khám, như BN này, lần đầu có xác định khám lao rồi, lập BA ok hết, thanh toán ok hết, nhưng khi lần sau đk tái khám, trên form đăng ký tái khám thì không load thông tin đk khám Lao của lần đầu lên để ghi nhận dữ liệu, dẫn đến nó như là khám thường. 
Data: binh_ttytnk.
Mã BA: N2023000221
![image](https://user-images.githubusercontent.com/99630883/236362732-decb7e6e-9fa4-4fed-91bb-9ab0d166790b.png)
![image](https://user-images.githubusercontent.com/99630883/236362901-ad4ab789-939c-4bb1-b280-4ffd74e9b3c4.png)

**Comment by lqbinh1987** [comment]
Này sao rồi a @nghivanbi ?

**Comment by lqbinh1987** [comment]
Hỗ trợ này dùm em nhe anh @nghivanbi

**Comment by lqbinh1987** [comment]
tranh thủ coi này dùm em anh @nghivanbi .

**Comment by minhduc2it** [comment]
Chỗ này Trạm đang bị lỗi khi gửi cổng BH
BÁn ngoại trú Lao khi Đăng ký tái khám không có check Khám Lao gửi cổng báo lỗi

**Comment by nghivanbi** [comment]
ok

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.23.0531.1](http://www.fsend.vn/download/ZrfZt2geAOoB5gmOz0hla-4kcebFheWq)

**Comment by lqbinh1987** [comment]
Coi chổ mở ra cho chỉnh ngày dùm em he anh @nghivanbi .
