### ISSUE TITLE
Yêu cầu - IN chỉ định CLS của KSK CTY

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalregister#4]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92127`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Medic Hòa Hảo CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_hoahao_inphieu_chuathutien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Chổ in phiếu chỉ định CLS để xác nhận đăng ký cho BN KSK CTY, yêu cầu in theo mẫu tự thiết kế.
Mã BN: 2022000007
Mã cty: 03 

![image](https://user-images.githubusercontent.com/99630883/181183584-6150097b-0a01-49ce-9a83-f200aac8b4ff.png)

**Comment by nghivanbi** [comment]
ok để cập in theo mẫu.

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.0729.1](http://www.fsend.vn/download/q6zcED_7sCoDXthqJbPup2sVwaF7j0Z_)
