### ISSUE TITLE
Yêu cầu - Thống kê chỉ định CLS ngoại trú BN nhập viện; CLS miễn phí và 0 đồng.

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalregister#40]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Ung Bướu**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Thống kê chỉ định CLS ngoại trú của BN nhập viện
Thống kê chỉ định CLS miễn phí và 0 đồng
Đính kèm file đề nghị Bv Ung Bướu

```
[Đề nghị hỗ trợ thống kê.docx](https://github.com/dh-hos/dhg.hospitalregister/files/11866202/D.ngh.h.tr.th.ng.ke.docx)

**Comment by lqbinh1987** [comment]
Đề nghị thứ 2: Hiện có check  để thống kê CLS miễn phí rồi, nhưng có check thống kê CLS 0 đồng, đề nghị thêm check CLS 0 đồng(Không bao gồm XN con).
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/99630883/49169b2d-c8a7-4fe8-889b-00be663df662)
