### ISSUE TITLE
Lỗi - Nhận BN trái tuyến

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalregister#41]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `70082`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK 123 Hùng Vương**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_123hv2020005153_2304002545_`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023004054` - _**MaKB**_: `2304002639` - _**MaBA**_: `MaBA` _**NgayKCB**_: `29/06/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `04` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

MÃ BV khám hiện tại là tuyến Huyện, nhưng nhập Mã thẻ là tuyến Tỉnh và lưu lại thì pm lại không cảnh báo như trước có giấy chuyển viện hay không?????
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/99630883/97846176-923b-45fa-803b-0f5670920796)

**Comment by lqbinh1987** [comment]
Nhờ a @nghivanbi coi dùm em, vì hiện tại TYT cũng bị.

**Comment by chauthanhtra** [comment]
- TYT và BV tuyến Huyện hiện tại đang ký khám bệnh có nhập giấy chuyển (lúc nhận bệnh và hiệu chỉnh thông tin) không chỉnh qua trạng thái cùng tuyến được
- TYT nhập thẻ của BV tuyến tỉnh phải là trái tuyến nhưng hiện tại phần mềm ghi nhận là Trái tuyến được hưởng cùng tuyến

**Comment by lqbinh1987** [comment]
Anh @nghivanbi coi cái này dùm e.

**Comment by nghivanbi** [comment]
Cập nhật:
Register:[ v3.23.0710.1](http://www.fsend.vn/download/mTWPMEQ3oUVieUdUEqPWUIljrX1J0oRk)

**Comment by nghivanbi** [comment]
Cập nhật: fix lỗi thông báo 2 lần.
Register: [v3.23.0711.1 ](http://www.fsend.vn/download/7H3PxOJsAjSFEz3ddj357KRcx4iXtzHM)

**Comment by lqbinh1987** [comment]
Test lại trường hơp của e lun nhe @chauthanhtra
