### ISSUE TITLE
Lỗi - Khi quét mã CCCD hoặc nhập mã CCCD không lấy lại đc số Điện thoại người bệnh đã nhập lúc đầu

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalregister#45]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `93102`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa Khoa số 10**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbso10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023025562` - _**MaKB**_: `2309006931` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/09/2023` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Bệnh nhân đăng ký lúc đầu có nhập số điện thoại như hình dưới
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/97272364/79da16f5-2253-4789-898c-68be26a947f8)
Khi đăng ký lại quét mã CCCD hoặc gõ lại mã CCCD thì load lại thiếu cột Điện thoại và Phường xã như hình dưới
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/97272364/0fb53f26-3e55-4e28-af39-8412c6e0c2fd)

Nếu nhập lại bằng mã bệnh nhân hoặc tìm theo tên bệnh nhân thì load lại thông tin củ bình thường

**Comment by ongtrieuhau** [comment]
@nghivanbi fix gấp cái này giúp em, vì ban giám đốc lên tiếng rồi

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3,23,0911.1](http://www.fsend.vn/download/-5yemHPwZypQBAshVVa-9Qi09m3fcuSg)

**Comment by hvtuan1987** [comment]
ok rồi á anh !
