### ISSUE TITLE
Lỗi - Register hiển thị sai mã ICD chính khi đăng ký tái khám BANT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalregister#49]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92137`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Ninh Kiều**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_so10_ravientt18`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/rLwZ7EgQx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023028055` - _**MaKB**_: `2309009941` - _**MaBA**_: `N2023000001` _**NgayKCB**_: `21/09/2023` - _**MaPhong**_: `KC1` - _**MaDV**_: `04` - _**ThangKT**_: `09` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi đăng ký tái khám BANT theo ngày trên Register 
Phần thông tin chẩn đoán cũ Mã ICD lại hiển thị mã nhân viên khám bệnh lần khám trước ( bnnoitru.manv )

( Test trên dữ liệu BV Số 10 )
```
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/9275feed-dafe-49c6-8169-fcc48ce8bdac)
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/e7c0a2ff-08cc-45bd-9a40-0c30f0eaf0aa)

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/91751241/72533860-57b5-4cd0-bf38-16701ca6c965)
Check lại bản mới nhất tại đây nha.

**Comment by chauthanhtra** [comment]
Không có quyền truy cập anh @nghivanbi ơi
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/aab19aa8-f51d-4a03-8125-fb0d76f81830)

**Comment by nghivanbi** [comment]
thử lại nhé

**Comment by chauthanhtra** [comment]
vào được rồi anh
