### ISSUE TITLE
Lỗi - Thao tác ghi nhận tuyến XML bị sai

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalregister#50]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquan12_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023012028` - _**MaKB**_: `2309004634` - _**MaBA**_: `MaBA` _**NgayKCB**_: `19/10/2023` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

https://github.com/dh-hos/dhg.hospitalregister/assets/99630883/bbe4ac37-1e93-4cd6-a2fb-9ac44d2ee20b

Sau khi nhập nơi đăng ký ban đầu, BV khám bệnh là BV tuyến Huyện, nhập nơi đăng ký ban đầu là BV tuyến Tỉnh(cùng địa bàn Tỉnh) PM hiện chữ Trái tuyến màu đỏ(để xác định ghi nhận psdangky.tuyenxml), nhưng sau đó chỉnh lại nơi đăng ký ban đầu là BV Tuyến huyện(cùng địa bàn Tỉnh) thì chữ **Trái tuyến màu đỏ vẫn còn hiện**, lưu dữ liệu thì vẫn sai luôn => dữ liệu psdangky.tuyenxml=1.

**Comment by lqbinh1987** [comment]
Coi dùm em lỗi này nhe anh @nghivanbi

**Comment by lqbinh1987** [comment]
Anh @nghivanbi coi dùm em

**Comment by nghivanbi** [comment]
Cập nhật: Register [v3.23.1108.1](https://drive.google.com/drive/folders/15qNx6iZavpvO9PHl--bCKCwfUNAR0v6y)

**Comment by lqbinh1987** [comment]
Câp nhật lên Pre dùm em lun nhe anh @nghivanbi

**Comment by nghivanbi** [comment]
Cập nhật: Prescription[ v3.23.1109.1](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3)
