### ISSUE TITLE
Lỗi - Ghi nhận dữ liệu BANT khi đã đăng ký tái khám.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalregister#51]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhtri_st_2023_02_10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2013004541` - _**MaKB**_: `2303000013` - _**MaBA**_: `N2023000139` _**NgayKCB**_: `07/11/2023` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Thao tác đăng ký tái khám BANT thanh toán theo ngày **khi hạn dùng của thẻ đã hết hạn**:
Ví dụ 2 máy tính cùng đang mở form đăng ký tái khám BANT, thực hiện trình tự như sau.
1. Ở máy tính số 1 nhấn Chọn tên BN, nhấn **Chỉnh hạn** để cập nhạt hạn dùng mới của thẻ và Lưu(hình 1), sau đó chọn Phòng và đăng ký tái khám vô phòng khám luôn. Dữ liệu thông tin thẻ được cập nhật vào 3 bảng **psdangky, bnnoitru, dmthebhyt**
2. Khi máy số 1 vào khám bệnh cho BN đó xong, có ra toa thuốc, => Ở máy tính số 2 , ở danh sách đăng ký tái khám BANT vẫn còn tên bn đó(do không nhấn làm mới dữ liệu lại), vẫn có thể thao tác chỉnh hạn dùng thẻ của tên BN đã đăng ký ở máy tính số 1, chỉ chỉnh hạn dùng thẻ và lưu lại chứ không đang ký tái khám vì không đăng ký được nữa(máy số 1 đã đăng ký) => Lúc này pm sẽ cập nhật dữ liệu thông tin thẻ vào 2 bảng **bnnoitru, dmthebhyt** => không đồng nhất dữ liệu 3 bảng **psdangky, bnnoitru, dmthebhyt**.
Đề nghị: Kiểm tra và chặn không cho chỉnh hạn dùng kh BN đã đăng ký tái khám hoàn tất trong ngày.

Hình 1:
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/99630883/e1ef1c58-8bd5-4360-9a37-1987bc47cf9f)

**Comment by lqbinh1987** [comment]
coi dùm em Anh @nghivanbi

**Comment by nghivanbi** [comment]
Cập nhật: Prescription [v3.23.1120.1](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3)
