### ISSUE TITLE
Lỗi - Sai mã lý do vào viện.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalregister#6]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quôc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Huyện Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_saimalydovv`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2010006645` - _**MaKB**_: `2208005316` - _**MaBA**_: `MaBA` _**15/08/2022**_: `` - _**MaPhong**_: `19` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi tiếp nhận BN có thẻ BHYT đăng ký tại BV tuyến Tỉnh cùng địa bàn hoặc ngoài Tỉnh, theo CV 627 thì ghi nhận **XM1.MA_LYDO_VVIEN=3**.
Hiện chổ nhận bệnh còn thông báo chọn có giấy chuyển viện hay không? Người dùng lỡ tay chọn Có thì dẫn đến ghi nhận **psdangky.tuyenxml** bị sai.
Đề nghị bổ sung tham số để mặc định khi tiếp nhận BN có thẻ BHYT đăng ký tại BV tuyến Tỉnh cùng địa bàn hoặc ngoài Tỉnh thì không hiển thị thông báo hỏi có giây chuyển viện nữa và set **psdangky.tuyenxml=1** lun. để BV tùy chọn tham số tiện cho việc kiểm tra.

**Comment by lqbinh1987** [comment]
Thực hiện theo quy chế và nội quy mới ngày 25/08/2022.

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.0908.2](http://www.fsend.vn/download/U9HcLplSYn7bpUlL6x-kfgkkUbT_wDDI)
