### ISSUE TITLE
Lỗi - BANT Lao đăng ký tái khám sai tuyenxml

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalregister#61]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92027`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trạm Xuân Khánh**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tyt_xuankhanh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/dVIRhVmQo

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000047` - _**MaKB**_: `2401000029` - _**MaBA**_: `N2024000001` _**NgayKCB**_: `24/01/2024` - _**MaPhong**_: `01` - _**MaDV**_: `01` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
mo_ta_loi

```
Bệnh nhân khám Lao Khi đăng ký khám có Giấy chuyển (Cùng Tuyến)
Ngày đăng ký lần đầu 03/01/2024: Bảng psdangky cột tuyenxml =0
Ngày đăng ký tái khám BANT 24/01/2024: Bảng psdangky cột tuyenxml =1

![image](https://github.com/dh-hos/dhg.hospitalregister/assets/98437757/eca0d793-2b05-4741-888f-d32114493981)

![image](https://github.com/dh-hos/dhg.hospitalregister/assets/98437757/99be2fe0-7334-4219-ba58-5cc26d4581c5)

(Hiện tại cổng báo lỗi hồ sơ mức hưởng)

**Comment by nghivanbi** [comment]
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Register</h2>
 <h2>Ver: 3.24.04.26.1</h2>
  
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
 [![Build Status](https://img.shields.io/badge/Tải%20file%20cài%20đặt-NAS-blue?logo=googledrive)](https://gofile.me/78TQg/IB9slXJ5L)
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalregister/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by minhduc2it** [comment]
From Đăng ký BANT > Cột Mã BA > Khóa lại
Hiện tại mã BA có thể xóa được

![image](https://github.com/dh-hos/dhg.hospitalregister/assets/98437757/baa19634-b599-4402-96b0-26e1ef76b76c)

![image](https://github.com/dh-hos/dhg.hospitalregister/assets/98437757/57e53fed-de7b-4c14-ad15-ed3f04105cb8)

**Comment by minhduc2it** [comment]
Đã kiểm tra cột Mã BA không cho xóa
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/98437757/4a12bfc4-9563-481f-a187-02ab4970dca3)
 
Kiểm tra các chức năng cơ bản: Đăng ký, khám bệnh, in 01 chưa ghi nhận bất thường
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/98437757/f7f1f19c-5086-4cb8-a02c-66bc73f38851)
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/98437757/fca7ed54-f94a-4d5c-95d7-cff80999c7da)
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/98437757/5ffff133-88b9-42ef-becd-bd1526cb5721)
