### ISSUE TITLE
Lỗi - Nhận bệnh hiển thị sai giới tính khi chỉnh thông tin rồi bỏ qua

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalregister#64]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_nghiahanh_chinhtuoi_10042024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/fs8W1PEo2)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024006107` - _**MaKB**_: `2404001397` - _**MaBA**_: `MaBA` _**NgayKCB**_: `22/4/2024` - _**MaPhong**_: `1` - _**MaDV**_: `10` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phần mềm Register và Prescription bị lỗi giống nhau

Khi nhận bệnh nếu bệnh nhân có giới tính là Nam hoặc Chưa xác định. Bấm Chỉnh -> Bỏ qua -> Giới tính bệnh nhân hiển thị thành Nữ (chỉ sai trên form, dữ liệu vẫn ghi nhận đúng) nhưng nếu bấm Chỉnh tiếp rồi Lưu lại thì giới tính bệnh nhân chuyển thành Nữ
       -> Nếu người nhận bệnh không để ý thì sẽ sai thông tin giới tính của bệnh nhân

-> Đề nghị hiển thị đúng giới tính của bệnh nhân khi bấm Chỉnh rồi bấm Bỏ qua.

![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/2701df24-ffad-46cb-804b-e63ff4c57a1b)
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/b6b53451-fc1e-4908-b8cb-5589574e450b)
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/b2abbbd9-75ff-4542-88dc-3b53289afd31)
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/ee003c28-9994-418c-9883-7340e98a357b)
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/94f12c02-d58f-4167-a49f-db1cfb859d70)
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/6ae8742d-20aa-4748-b96f-2cfc8fb69e44)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalregister/64)
<details> <summary>   ℹ️<code>2024-22-04 15:35:14</code> <code>@chauthanhtra</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-Nw3wUF49e7lv0HZLsbq'>-Nw3wUF49e7lv0HZLsbq</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1713773398965</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8780666411'>webhook-logs</a>]</code></details>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0908.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32409080-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32409080-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32409080-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi sai giới tính khi chỉnh thông tin bệnh nhân

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/64

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
![](https://i.imgur.com/8ixKRyA.png)
![](https://i.imgur.com/KW4ufkT.png)

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '  16/9/2024  '.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm HospitalRegister.exe v.3.24.0916.0
Phần mềm Prescription.exe v.3.24.0915.0
***
>Lỗi, yêu cầu đã hoàn thành 

- Nội dung: 

  - Phần mềm Register và Prescription mới đã fix lỗi sai giới tính form nhận bệnh khi bấm chỉnh rồi bở qua
  - Test dữ liệu bệnh nhân BHYT mới chỉ định CLS, thuốc, in bảng kê, xuất XML bình thường, chưa phát hiện lỗi mới

- Hình ảnh: 

![ảnh](https://github.com/user-attachments/assets/8efa8ab1-b085-4b1a-9a27-21b296d6dc9b)
![ảnh](https://github.com/user-attachments/assets/cd2ce89a-6b4b-45bd-89a1-07abf09cb5e3)
![ảnh](https://github.com/user-attachments/assets/969f1c2e-50d9-441d-a674-998e2ea34cf1)
![ảnh](https://github.com/user-attachments/assets/66e5daf1-f2ce-4e7d-8851-b9fae0d73f4a)
![ảnh](https://github.com/user-attachments/assets/71a4b258-0396-4bc6-b0fe-291c3f2959df)
![ảnh](https://github.com/user-attachments/assets/f0148939-e390-439e-ba17-f98118d1c2f3)

![](https://i.imgur.com/V1sroyr.png)
![](https://i.imgur.com/AbeMdrx.png)
![ảnh](https://github.com/user-attachments/assets/cff28d2f-a80f-4d4c-b740-2c8d0b098034)
![ảnh](https://github.com/user-attachments/assets/61853c6e-53bc-48d5-a850-442bf3fcd8ef)


***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

>- Diễn giải lỗi:


>- Hình ảnh lỗi:



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
