### ISSUE TITLE
Lỗi - khi tiếp nhận có thông tin chuyển tuyến dưới nhưng không chọn hình giấy Chuyển tuyến

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalregister#65]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện chuyên khoa Sản Nhi Sóc Trăng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbsannhist_loitiepnhan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi tiếp nhận thông tin bệnh nhân có giấy chuyển tuyến từ tuyến dưới nhưng không chọn hình giấy Chuyển tuyến khi bấm Nút Lưu báo lỗi như hình dưới.
Hình bệnh nhân khác em có nhập Thông tin và có kèm theo hình giấy Chuyển tuyến của tuyến dưới thì Lưu bình thường.
Đề nghị cho option tùy chọn để làm sao khi thao tác test 130 này không ảnh hưởng đến thao tác lưu dữ liệu bình thường của 4210 hiện tại.

![image](https://github.com/dh-hos/dhg.hospitalregister/assets/97272364/e5cbbb94-78bc-427f-9f73-6f5711521456)

Chi tiết lỗi:
Phiên bản :2024.04.18.134228PM
System.ArgumentException: Empty path name is not legal.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at HosReg.Code.Forms.FrmDangKyBH.setPsDangKy()
   at HosReg.Code.Forms.FrmDangKyBH.setDmBenhNhan()
   at HosReg.Code.Forms.FrmDangKyBH.btnClick(Object sender, EventArgs e)

![image](https://github.com/dh-hos/dhg.hospitalregister/assets/97272364/222b043a-4aaa-4d1c-a22e-2d4871acd7ae)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalregister/65)

**Comment by lqbinh1987** [comment]
Anh @nghivanbi  coi dùm tổ em.

**Comment by hvtuan1987** [comment]
Nào rảnh check dùm em lỗi này á anh @nghivanbi !

**Comment by le-an-87** [comment]
alo anh @ongtrieuhau ơi. chổ này anh coi chỉnh giùm không bắt buộc nhập giấy chuyển viện và giấy cư trú giùm em anh ơi.
hiện tại các bệnh viện không cần bắt buộc phải scan giấy này vô.

-> đề xuất thêm cảnh báo, không bắt buộc

**Comment by nghivanbi** [comment]
ok nay anh đang coi

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/91751241/4363c963-951a-4697-8883-62960ddc7f63)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0612.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406120-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406120-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406120-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Không bắt buộc chọn giấy lưu trú và giấy lưu chuyển tuyến

- ☑:  https://github.com/dh-hos/dhg.hospitalregister/issues/65

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0612.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406122-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406122-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406122-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Không bắt buộc chọn giấy lưu trú ngay cả khi có xác nhận lưu trú

- ☑:  https://github.com/dh-hos/dhg.hospitalregister/issues/65

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/91751241/98df5dfb-cbe8-49df-8ef1-02bcc2757f37)

**Comment by hvtuan1987** [comment]
Đã fix ok rồi á !
![Uploading image.png…]()
