### ISSUE TITLE
Lỗi - 1. Phiếu chỉ định CLS tự thiết kế không in được ngày giờ in phiếu và phong khám. 2. Sai định dạng ngày ký phiếu chỉ định CLS thủ thuật, phẫu thuật, DV

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalregister#66]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **7/5/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quân Dân Y Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_saidinhdangngaygio_phieuchidinhcls_reg_02052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/poIVGO4dP)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024005373` - _**MaKB**_: `2405000256` - _**MaBA**_: `MaBA` _**NgayKCB**_: `2/5/2024` - _**MaPhong**_: `09` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `TH5096` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Khi in phiếu chỉ định CLS tự thiết kế  tham số phieuycchuan = 2 trên Register thì không in được ngày giờ in phiếu và phòng khám (Prescription in được bình thường),

![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/62f4e399-9f66-4ba1-a55a-931dcc6d2a6b)
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/3a259ee4-a6d4-4219-a4c8-757eec5f1277)
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/e29f8e61-f675-4e97-9f74-8cebc58f15fc)

2. Khi in phiếu chỉ định CLS mặc định tham số phieuycchuan = 0 trên Register  loại phiếu Phẫu thuật, thủ thuật, dịch vụ thì Register thể hiện ngày tháng ký theo định dạng ngày tháng trên máy tính in phiếu (các mẫu khác mặc định định dạng ngày tháng ký là ngày/tháng/năm , chỉ bị lỗi trên Register, Prescription mặc định ngày ký luôn là ngày/tháng/năm)
-> Thống nhất định dạng ngày ký tên mặc định là ngày/tháng/năm không theo định dạng ngày tháng máy tính (1 số máy tính không chỉnh được định dạng ngày tháng về ngày/tháng/năm)

![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/956f3ca1-9ebc-4ab5-9562-0350d15c6bfd)
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/50381b18-1b7a-40aa-a999-aa5c9652ea3b)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalregister/66)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0630.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406301-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406301-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406301-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi mất ngày giờ in phiếu chỉ định cận lâm sàng tự do

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/66

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/91751241/934aeb82-5147-4b82-a3a0-c98e162a00e0)

**Comment by chauthanhtra** [comment]
- Register in mẫu mặc định thì ngày giờ trên phiếu đã đúng định dạng ngày tháng năm
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/2ee0d069-22f5-49a4-889c-5ec193b67d8a)

- Register in mẫu tự thiết kế vẫn chưa lấy được ngày giờ in và phòng khám
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/ea5c2874-e21a-4697-8756-b1686842262a)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0630.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406302-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406302-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406302-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi mất ngày giờ in phiếu chỉ định cận lâm sàng tự do

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/66

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
Again dùm anh cái @chauthanhtra

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0630.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406303-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406303-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32406303-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi mất ngày giờ in phiếu chỉ định cận lâm sàng tự do

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/66

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- Đã fix lỗi ngày giờ in phiếu trên phiếu chỉ định CLS tự do tự thiết kế

![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/c9d044f2-771b-481e-9e21-556b4f1e8e2e)

- Mẫu mặc định sai định dạng ngày giờ phiếu thủ thuật PT dịch vụ. để IT check lại rồi thông báo sau

![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/97272332/1dd380ab-1283-4e86-9cc2-0dbbc7e4c07c)

**Comment by chauthanhtra** [comment]
BV chuyển qua sử dụng mẫu tự thiết kế. không tìm thấy lỗi mới
