### ISSUE TITLE
Lỗi - Xác định lý do vào viện trên bảng kê 6556

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalregister#69]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_130_tohotro_issues_20`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > **NgayKCB**_: `05/06/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
### Ngoại trú
   > **MaPhong**_: `01` - _**MaDV**_: `10` 
### Nội trú
   > **MaDV**_: `15` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Đề nghị xác định lại lý do vào viện (check đúng tuyến, thông tuyến, cấp cứu, trái tuyến) trên bảng kê 6556 đối với bệnh nhân ngoại trú và nội trú.
hiện tại có 1 số trường hợp không đúng với công văn 627/BYT-BH

 A. Ngoại trú (bảng kê 6556)
  1.  Bệnh nhân nhập giấy chuyển viện  -> Thông tuyến
  2.  Thẻ đăng ký tại bv huyện khác  trong tỉnh lại khám -> đúng tuyến
  3. Thẻ đăng ký bv huyện ngoại tỉnh lại khám ->đúng tuyến
B. Nội trú (bảng kê 6556)
  1. Thẻ đăng ký bv huyện ngoại tỉnh lại khám -> Thông tuyến
  2. BV có giấy chuyển viện -> trái tuyến
  3. Chưa hỗ trợ bệnh nhân có nhập giấy lưu trú.

*** Chổ này dính đến nhiều git nên mấy anh xem thống nhất lại cách làm sớm nhe!
- mô tả chồng chéo với nhau không tổng quá được như: mô tả 627 và CÁCH GHI NHẬN GIÁ TRỊ CỘT XML1.MA_LYDO_VVIEN (cột 16, bảng 1 - XML4210).

các git đang vướng
https://github.com/dh-hos/dhg.hosptaltreatment/issues/209

https://github.com/dh-hos/dhg.hosptaltreatment/issues/216

https://github.com/dh-hos/Yeu_cau_ho_tro/issues/12
```
một số hình ảnh hướng dẫn theo cv 627
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/96155021/04a52c0b-d83b-4dae-ab38-d1e1d0dff507)

## A. Ngoại trú (bảng kê 6556)
  1.  Bệnh nhân nhập giấy chuyển viện  -> Thông tuyến
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/96155021/68bb33e5-c1f8-42c0-a71c-cf094ee3cbcd)
  2.  Thẻ đăng ký tại bv huyện khác  trong tỉnh lại khám -> đúng tuyến
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/96155021/945ab42c-edb6-4f4b-8c5c-7b56534e5305)
  3. Thẻ đăng ký bv huyện ngoại tỉnh lại khám ->đúng tuyến
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/96155021/0d68dcc5-3bbe-4ba8-969c-3ed8cdb475f6)
   
## B. Nội trú (bảng kê 6556)
  1. Thẻ đăng ký bv huyện ngoại tỉnh lại khám -> Thông tuyến
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/96155021/3209901f-d004-42c6-bf7e-86234992213e)
  2. BV có giấy chuyển viện -> trái tuyến
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/96155021/fd228ebc-42dd-4580-91ae-11e8707fd681)
  3. Chưa hỗ trợ bệnh nhân có nhập giấy lưu trú.
![ảnh](https://github.com/dh-hos/dhg.hospitalregister/assets/96155021/7cf61c4d-c182-4032-a742-d2f34d58913e)

**Comment by vuongdh** [comment]
@le-an-87 em xác định lại dùm các issue nào là lỗi thì chỉnh theo hướng dẫn của công văn không cần phải bàn
Cái nào là yêu cầu thì xác định làm thì làm thôi. Cái nào cần bàn thì em đưa vào issue riêng hén

P/s: Mấy lỗi nào treatment còn vướng, em comment vào để anh theo dõi nha. Cám ơn em.

**Comment by le-an-87** [comment]
chuyển sang xử lý git https://github.com/dh-hos/To_Lap_Trinh/issues/389.
