### ISSUE TITLE
Lỗi - LẤY SAI MÃ KB KHI QUÉT CẤP STT PHÁT THUỐC TRÊN ORDINAL, BẢNG KÊ KHÔNG THẤY STT ĐỂ IN

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalregister#72]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT HUYỆN TRÀ CÚ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbtracu_072024062024052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](hoa_dbtracu_072024062024052024)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018000866` - _**MaKB**_: `2407003713` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

khi quét cấp STT tại Ordinal phân khu phát thuốc insert sai makb toàn bộ các bệnh nhân.

![image](https://github.com/dh-hos/dhg.hospitalregister/assets/130281806/0fb8aba0-8a79-4de9-81d1-283617c906ed)
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/130281806/61e5b600-13f5-47c9-9e13-634636a5b7c0)
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/130281806/3f8e5bcc-7ce6-4469-ad5d-d68d180dc68a)

các BN ngoài BN đã test có 1 số BN insert makb năm 2018
![image](https://github.com/dh-hos/dhg.hospitalregister/assets/130281806/54370335-8825-491f-a004-8cf3358f06bb)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix lỗi - Lỗi - LẤY SAI MÃ KB KHI QUÉT CẤP STT PHÁT THUỐC TRÊN ORDINAL, BẢNG KÊ KHÔNG THẤY STT ĐỂ IN.
-  📆 **Thời gian hoàn thành :**  2024-07-10.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 RegisterOrdinal.exe v.1.24.0709.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FRegisterOrdinalexe%2F12407090-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FRegisterOrdinalexe%2F12407090-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FRegisterOrdinalexe%2F12407090-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - LẤY SAI MÃ KB KHI QUÉT CẤP STT PHÁT THUỐC TRÊN ORDINAL, BẢNG KÊ KHÔNG THẤY STT ĐỂ IN #72

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/72

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/RegisterOrdinal.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
Ghi nhận bị thiếu STT trên bảng kê trên kho đông y >> đã thể hiện đầy đủ
![image](https://github.com/user-attachments/assets/d2870a94-f69e-4e1f-a26a-8ff3200d0e19)
