### ISSUE TITLE
Lỗi - SAI TRẠNG THÁI CHUYỂN TUYẾN KHI ĐĂNG KÝ TÁI KHÁM BANT

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalregister#73]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92137`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Ninh Kiều**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_ninhkieu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/QV2ZBm9hv

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000195` - _**MaKB**_: `2407000058` - _**MaBA**_: `N2024000179` _**NgayKCB**_: `15/07/2024` - _**MaPhong**_: `06` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

**Bệnh nhân khám Lao Khi đăng ký khám có Giấy chuyển (Cùng Tuyến)** 
**- Ngày khám lần đầu** 15/07/2024 đăng ký có nhập Thông tin Giấy chuyển tuyến - xử trí BANT bảng psdangky ghi nhận dữ liệu:
         maicdtd = A15
        cdoantd = Lao hô hấp, có xác nhận về vi khuẩn học và mô học
        socttd = 123
        trangthaichuyentuyen = 4
        tungaytd = 15/07/2024
        denngaytd = 31/07/2024
**- Ngày đăng ký tái khám BANT** 16/07/2024 bảng psdangky ghi nhận dữ liệu:
      maicdtd = Null
      cdoantd = Lao hô hấp, có xác nhận về vi khuẩn học và mô học
      socttd = Null
      trangthaichuyentuyen = Null
      tungaytd = Null
      denngaytd = Null

**Yêu cầu khi đăng ký tái khám BANT  các thông tin **Null** lấy dữ liệu theo lần đăng ký đầu tiên**

![image](https://github.com/user-attachments/assets/c437644b-7d41-4c76-a162-ebb12878bf7c)

**Comment by ongtrieuhau-dh** [comment]
Cái này xác định lỗi hay yêu cầu cụ thể nha @minhduc2it

**Comment by minhduc2it** [comment]
> Cái này xác định lỗi hay yêu cầu cụ thể nha @minhduc2it

Lỗi nha anh

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-18**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix lỗi - SAI TRẠNG THÁI CHUYỂN TUYẾN KHI ĐĂNG KÝ TÁI KHÁM BANT.
-  📆 **Thời gian hoàn thành :**  2024-07-18.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0718.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407180-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407180-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407180-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Nhận bệnh trên Register bắt nhập thiếu Trạng thái Chuyển tuyến

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/74

- 🐛: Fix lỗi sai thông tin chuyển tuyến khi đăng ký tái khám BANT

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/73

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Đăng ký Tái khám BANT các thông tin Null chưa lấy dữ liệu theo lần đăng ký trước đó nha @lequocthong29 

![image](https://github.com/user-attachments/assets/60688003-f60f-42e2-8a46-12947249a438)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0719.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407191-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407191-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407191-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - đăng ký tái khám BANT các thông tin Null lấy dữ liệu theo lần đăng ký trước đó

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/73

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lequocthong29** [comment]
@minhduc2it thử lại nha a

**Comment by minhduc2it** [comment]
Đã kiểm tra Đăng ký Tái khám BANT thông tin Chuyển tuyến đã lấy theo lần đăng ký trước đó
![image](https://github.com/user-attachments/assets/f13993b0-4ac2-458a-a386-f77583992115)

Các chức năng cơ bản khác: Đăng ký, khám bệnh chưa ghi nhận bất thường. In 01 do postgres lỗi oid nên chưa in thử được 01

![image](https://github.com/user-attachments/assets/39449d54-7d07-4ff2-b472-c5e3625fc4fb)

![image](https://github.com/user-attachments/assets/14baaeb6-2b4e-4989-bef6-931ce7c35e4b)
