### ISSUE TITLE
Lỗi - Nhận bệnh trên Register không bắt nhập thiếu Trạng thái Chuyển tuyến

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalregister#74]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92137`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Ninh Kiều**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_ninhkieu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/QV2ZBm9hv

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000198` - _**MaKB**_: `2407000063` -_**NgayKCB**_: `17/07/2024` - _**MaPhong**_: `06` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

**1. Nhận bệnh trên Register không bắt nhập thiếu Trạng thái Chuyển tuyến** [(Cùng lỗi với đăng ký trên Prescription)](https://github.com/dh-hos/dhg.hospitalprescription/issues/277)

![image](https://github.com/user-attachments/assets/aa103891-612c-4cba-a92a-69ae13a08727)

**2. P/s: Số chuyển và Điều trị từ  ... đến ngày ...**  nếu nhập thiếu thông tin Có cảnh báo bắt nhập
(Đảm bảo dữ liệu chuyển tuyến được nhập đầy đủ)

![image](https://github.com/user-attachments/assets/88b4f097-c0a8-4970-95f0-38f03a2b1f95)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-19**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix lỗi - Nhận bệnh trên Register không bắt nhập thiếu trạng thái chuyển tuyến.
-  📆 **Thời gian hoàn thành :**  2024-07-19.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0718.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407180-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407180-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407180-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Nhận bệnh trên Register bắt nhập thiếu Trạng thái Chuyển tuyến

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/74

- 🐛: Fix lỗi sai thông tin chuyển tuyến khi đăng ký tái khám BANT

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/73

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Còn thông tin **Số chuyển** và **Điều trị từ ... đến ngày ...** chưa có Cảnh báo bắt nhập nha @lequocthong29 

2. P/s: Số chuyển và Điều trị từ ... đến ngày ... nếu nhập thiếu thông tin Có cảnh báo bắt nhập
(Đảm bảo dữ liệu chuyển tuyến được nhập đầy đủ)

![image](https://github.com/user-attachments/assets/4157e473-553a-455e-a10e-218d44e89b50)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0719.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407190-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407190-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32407190-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Thêm cảnh báo - khi nhập chuyển tuyến thiếu số chuyển , điều trị từ.. đến ...

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/74

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Đã kiểm tra Cảnh báo bắt nhập: Số chuyển, điều trị từ ngày đến ngày, Trạng thái chuyển tuyến thành công 
Các chức năng khác chưa ghi nhận bất thường

![image](https://github.com/user-attachments/assets/ee8d15aa-945d-4a57-bd21-1e24964dc706)

![image](https://github.com/user-attachments/assets/5fb6f0e1-14cc-4c88-92ac-9640f5ec7ab8)

![image](https://github.com/user-attachments/assets/3246103b-44f8-41fb-86bf-5b4ab7676130)

**Comment by minhduc2it** [comment]
Các chức năng cơ bản khác: Đăng ký, khám bệnh chưa ghi nhận bất thường. In 01 do postgres lỗi oid nên chưa in thử được 01

![image](https://github.com/user-attachments/assets/39449d54-7d07-4ff2-b472-c5e3625fc4fb)

![image](https://github.com/user-attachments/assets/14baaeb6-2b4e-4989-bef6-931ce7c35e4b)
