### ISSUE TITLE
Lỗi - Prescription ghi nhận sai cột tuyen trong bnnoitru đối với bệnh nhân nhập viện trái tuyến tại BV tuyến tỉnh

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalregister#75]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbdalieuct_diachi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/hjZHtUwdx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024035296` - _**MaKB**_: `2407000002` - _**MaBA**_: `000002` _**NgayKCB**_: `19/07/2024` - _**MaPhong**_: `` - _**MaDV**_: `02` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

Những bệnh nhân nhập viện trái tuyến tại bệnh viện tuyến tỉnh (Không có giấy chuyển tuyến) theo mô tả hệ thống Prescription xử trí NHẬP VIỆN những bệnh nhân trái tuyến ghi nhận vào bảng bnnoitru với cột tuyen=1. Nhưng hiện tại Prescription ghi nhận cột tuyen=0 trong bảng bnnoitru nên so với mô tả. Dẫn đến ghi sai mã loại ĐỐI TƯỢNG KCB
Nhờ code kiểm tra lại trường hợp này
(Ghi chú: Lúc tiếp nhận thì ghi nhận đúng cột tuyen=1 tại bảng psdangky. )
![image](https://github.com/user-attachments/assets/ffe0acbc-09cf-4f8a-8aeb-95d38c099af0)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix -Prescription ghi nhận sai cột tuyen trong bnnoitru đối với bệnh nhân nhập viện trái tuyến tại BV tuyến tỉnh.
-  📆 **Thời gian hoàn thành :**  2024-07-26.

**Comment by hvtuan1987** [comment]
Xác nhận lại sai mô tả Quyết định 4750 nên hiện tại Prescription đang lấy đúng !
Gith dưới đnag mô tả lại !
https://github.com/dh-hos/dhg.hospitaladmin/issues/80
