### ISSUE TITLE
Lỗi - BV Tim Mạch CT: Chỉ định CLS tự do Thêm CLS lần 2 báo lỗi khi lưu

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalregister#78]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_ct_dia_phieutt_hinhsieuam_18092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/d98n34RMZ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `24000002` - _**MaKB**_: `2409012808` - _**MaBA**_: `MaBA` _**NgayKCB**_: `23/09/2024` - _**MaPhong**_: `01` - _**MaDV**_: `01` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi chỉ định CLS tự do bệnh nhân, thêm CLS lần thứ 2 lưu lại thì phần mềm báo lỗi (chỉ định 1 CLS xong lưu lại, xong bấm thêm CLS mới bấm lưu lại là báo lỗi) , bệnh nhân BH hay thu phí đều lỗi

![](https://i.imgur.com/fjPrj5t.png)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-09-24.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0923.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32409231-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32409231-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32409231-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Lỗi BV Tim Mạch CT: Chỉ định CLS tự do Thêm CLS lần 2 báo lỗi khi lưu

![](https://i.imgur.com/HPf1MAG.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/78

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm HospitalRegister.exe v.3.24.0924.0
***
>Lỗi, yêu cầu đã hoàn thành 

- Nội dung: 

  - Register mới đã fix lỗi chỉ định CLS tự do lần 2
  - Test bệnh nhân chỉ định CLS, cấp toa, in bảng kê, xuất XML bình thường

- Hình ảnh: 

![](https://i.imgur.com/g2tkXYb.png)
![](https://i.imgur.com/aHp2No4.png)
![](https://i.imgur.com/Zb134bu.png)
![](https://i.imgur.com/JpwPpYf.png)
![](https://i.imgur.com/D9wd6oO.png)
![](https://i.imgur.com/1a7C0o9.png)
![](https://i.imgur.com/uUEYZUW.png)

***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

> - Diễn giải lỗi:
>   - 
> 
> - Hình ảnh lỗi:
> 


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
