### ISSUE TITLE
Lỗi - CHỌN trangthaichuyentuyen = 6 (Giấy hẹn lãnh thuốc người bệnh lao) LỖI SO VỚI MÔ TẢ

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalregister#79]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92102`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trạm Tân Thạnh**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tanthanh`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/QcJapWHYK

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000774` - _**MaKB**_: `2410000008` - _**NgayKCB**_: `08/10/2024` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Theo [Mô tả XML130 - Bổ sung QĐ 4750.md](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md)
**Mục 1.** Riêng đối với người bệnh khám lao có giấy hẹn lãnh thuốc: khi chọn psdangky.trangthaichuyentuyen = 6 (Giấy hẹn lãnh thuốc người bệnh lao) thì hỗ trợ check chọn mặc định [Bệnh nhân khám lao] = true tại tab  [Khám lao], đồng thời không bắt buộc phải chọn mã bệnh viện nơi giới thiệu (psdangky.manoigt)

![image](https://github.com/user-attachments/assets/7a449921-cf6d-463d-a9e6-764867152ea5)

Khi đăng ký chỗ tab **Chuyển tuyến** > ô **T.thái** không cho chọn 
![image](https://github.com/user-attachments/assets/3421810a-f5e1-4ef7-a52c-b100d844c939)

**Mục 2.** Chỗ Mô tả tại **_Mục 1 (bên trên)_**: có thể áp dụng **Nếu Check khám Lao thì tự gán giá trị mặc định trangthaichuyentuyen = 6 VÀ ô T.thái hiển thị: Giấy hẹn lãnh thuốc - Lao**
![image](https://github.com/user-attachments/assets/1d6eaeb8-2690-433f-9c8b-13b42b294df4)

Ps: Thay vì phải áp dụng như Mục 1, người dùng mất khá nhiều thao tác để chọn.
Áp dụng như luồng [git này](github.com/dh-hos/THEO_DOI_THUC_HIEN/issues/108#issuecomment-2295563140) trước đây dễ cho người dùng Và nhất là tuyến Trạm 
![image](https://github.com/user-attachments/assets/5f7b74c4-e190-4f67-9dcf-a15a54a93425)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-10-14**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vinh-dh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Xem có cần cập nhật mô tả không?

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: tóm lại nội dung issu là như vầy phải không @minhduc2it 

- [ ] 1. Lỗi: Không chọn được trạng thái chuyển tuyến khi chưa chọn mã nơi giới thiệu (thực hiện chưa đúng theo mô tả)
- [ ]  2. Đề nghị:  Check khám Lao thì tự gán giá trị mặc định trangthaichuyentuyen = 6

🔈 Giải đáp:
***

**Comment by vinh-dh** [comment]
> Khi đăng ký chỗ tab Chuyển tuyến > ô T.thái không cho chọn
> ![image](https://github.com/user-attachments/assets/3421810a-f5e1-4ef7-a52c-b100d844c939)

@minhduc2it: Chỗ này là do Register làm sai so với mô tả:
![image](https://github.com/user-attachments/assets/c5f85261-2ac2-4141-b5a9-710f5e16c802)

@lequocthong29 em coi fix lại Register nhé!

> 2. Đề nghị: Check khám Lao thì tự gán giá trị mặc định trangthaichuyentuyen = 6

@le-an-87: không được, vì như vậy đối với BN khám lao (không lãnh thuốc) thì sẽ sai. Mô tả trên chỉ áp dụng đối với người bệnh khám lao đi lãnh thuốc.

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-11.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1009.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32410090-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32410090-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32410090-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Trường hợp bệnh nhân khám lao có giấy hẹn lãnh thuốc : khi chọn `psdangky.trangthaichuyentuyen = 6` (giấy hẹn lãnh thuốc người bệnh lao) thì hỗ trợ check chọn mặc định `[Bệnh nhân khám lao]` = true đồng thời không bắt buộc phải nhập mã bệnh viện nơi giới thiệu

![](https://i.imgur.com/kPLKX2U.png)

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/79`

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
-
Đã kiểm tra sửa lỗi hoàn thành

![image](https://github.com/user-attachments/assets/404460b9-948a-459c-a1ac-fbda2b15dcab)

Các chức năng khác chưa ghi nhận bất thường

**Comment by minhduc2it** [comment]
@lequocthong29 

Hiệu chỉnh thông tin trên Register chưa áp dụng T.Thái: khi chọn Giấy hẹn lãnh thuốc (lao) thì hỗ trợ check Khám Lao
![image](https://github.com/user-attachments/assets/60297ab2-a68d-4e40-9970-186648cba17f)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1010.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32410100-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32410100-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32410100-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Hiệu chỉnh thông tin - Trường hợp bệnh nhân khám lao có giấy hẹn lãnh thuốc : khi chọn psdangky.trangthaichuyentuyen = 6 (giấy hẹn lãnh thuốc người bệnh lao) thì hỗ trợ check chọn mặc định [Bệnh nhân khám lao] = true đồng thời không bắt buộc phải nhập mã bệnh viện nơi giới thiệu

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/79

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã kiểm tra sửa lỗi hoàn thành
![image](https://github.com/user-attachments/assets/8a132530-52fa-456f-830c-a9c7e20ac7e3)

**Comment by minhduc2it** [comment]
@lequocthong29 
Trường hợp: Đối với người bệnh khám lao có giấy chuyển tuyến: psdangky.trangthaichuyentuyen = 4 và psdangky.manoigt <> '' (Chuyển tuyến người bệnh khám và điều trị bệnh lao) thì hỗ trợ check chọn mặc định [Bệnh nhân khám lao] = true tại tab  [Khám lao] và psdangky.mabv_dieutri_lao = psdangky.manoigt
-
![image](https://github.com/user-attachments/assets/fbb0a62a-8902-4caa-a7a3-90e6cd810e70)

Có nhập mã nơi giới thiệu và chọn Trạng Thái: Chuyển tuyến người bệnh khám và điều trị bệnh lao
Phần mềm báo chưa nhập mã nơi giới thiệu
_Ps: Fix kèm Hiệu chỉnh thông tin chức năng này_
-
![image](https://github.com/user-attachments/assets/976e37d7-ffe3-443c-bd45-f07b3397df87)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1010.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32410101-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32410101-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32410101-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Đối với người bệnh khám lao có giấy chuyển tuyến: psdangky.trangthaichuyentuyen = 4 và psdangky.manoigt <> '' (Chuyển tuyến người bệnh khám và điều trị bệnh lao) thì hỗ trợ check chọn mặc định [Bệnh nhân khám lao] = true tại tab [Khám lao] và psdangky.mabv_dieutri_lao = psdangky.manoigt

- ☑: https://github.com/dh-hos/dhg.hospitalregister/issues/79

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã kiểm tra sửa lỗi hoàn thành
![image](https://github.com/user-attachments/assets/88971376-d649-4c32-ac88-ce89db781c27)
