### ISSUE TITLE
Lỗi - Lập phiếu nghĩ ốm không lấy được chẩn đoán khám bênh

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalregister#8]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_medicsaigon_phieunghiom`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000085` - _**MaKB**_: `2209001346` - _**NgayKCB**_: `12/09/2022` - _**MaPhong**_: `P14` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân đăng ký phòng khám P22 (không khám) sau đó chuyển sang phòng khám P24 để khám
-> Register khi lập phiếu nghĩ ốm không lấy được chẩn đoán của phòng khám cuối P24

```
Register khi lập phiếu nghĩ ốm không lấy được các chẩn đoán
![image](https://user-images.githubusercontent.com/96155021/189579169-afcae5ef-ac9d-4816-9812-94fd3ccacebc.png)
Khi lập phiếu tại Prescription
![image](https://user-images.githubusercontent.com/96155021/189579216-f64f433b-915b-481e-8503-b7b0dc92029a.png)

**Comment by nghivanbi** [comment]
Cập nhật: 
Register: v.3.22.09.14.2 luôn nha

**Comment by le-an-87** [comment]
Register mới làm phiếu nghĩ ốm báo lỗi này đó anh (đã cập nhật hết cấu trúc rồi)
![image](https://user-images.githubusercontent.com/96155021/190308623-12588519-26f1-4833-9c23-2bb3ea759221.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.09.15.1](http://www.fsend.vn/download/8fMjPc1lxOBEJCZWD-dgM7NQ2oKpw8bm)

**Comment by le-an-87** [comment]
đã fix!
