### ISSUE TITLE
Yêu cầu - TAB KHÁM LAO CHO HIỂN THỊ THÊM MỤC TRẠNG THÁI CHUYỂN TUYẾN

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalregister#80]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92102`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Yêu cầu áp dụng chung**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tanthanh`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/QcJapWHYK

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu: **tab Khám Lao** cho hiển thị thêm mục Trạng thái để chọn (Thay vì phải qua tab Chuyển tuyến để chọn Trạng thái) 
Và Ràng buộc thao tác nếu có Check khám Lao mà không chọn Trạng thái thì có Cảnh báo bắt phải chọn Trạng thái
- Ô chọn Trạng Thái bên tab Khám Lao chỉ cho hiển thị tùy chọn: Rỗng và Giấy hẹn lãnh thuốc (Lao) 
_Ghi chú: Nhằm Giảm thao tác và thuận tiện cho người dùng_ 
---
(Hình minh họa)
![image](https://github.com/user-attachments/assets/c8da279d-2b14-4716-aee3-6960a416bbb1)

**Comment by minhduc2it** [comment]
@nghivanbi anh xem dùm em yêu cầu này

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @minhduc2it 
-  📘 **Nội dung**: Này đã duyệt theo luồng yêu cầu rồi nhé.

**Comment by nghivanbi** [comment]
❓ XÁC NHẬN ❓
---------------------------------------------------------------------
-  👉 **Assign**: @minhduc2it 
-  📘 **Nội dung**: Xác nhận luồng yêu cầu trên đúng thì Close này đi nhé.

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Theo dõi cập nhật module theo yêu cầu này:

- [ ] https://github.com/dh-hos/To_Lap_Trinh/issues/699
